# Generated by Django 6.0.4 on 2026-04-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("platform_description", models.TextField()),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL for the candidate's photo", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_hash",
                    models.CharField(
                        help_text="SHA-256 hash to guarantee anonymity and prevent double voting",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("cast_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="voting.candidate",
                    ),
                ),
            ],
        ),
    ]
